nameOne = input()
nameTwo = input()
nameThree = input()
nameFour = input()
nameFive = input()
nameSix = input()
nameSeven = input()
nameEuth = input()

print('Побежали на качели')
print(nameOne, ",", nameTwo, ",", nameThree, ",", nameFour, ",")
print('Раскачали их на славу')
print(nameFive, ",", nameSix, ",", nameSeven, ".")
print('Загорал один', nameEuth, '.')
print('Лучше б он, как ты, водил!')